INSERT INTO EMPLOYEE
(ID, NAME, POSITION)
VALUES
(10001, 'Rinshad', 'Backend Engineer');

INSERT INTO EMPLOYEE
(ID, NAME, POSITION)
VALUES
(10002, 'Ammad', 'Full Stack Engineer');

INSERT INTO EMPLOYEE
(ID, NAME, POSITION)
VALUES
(10003, 'Fouzan', 'Marketing Manager');